import styled from "styled-components"

export const Classify = styled.div`
position:absolute;
top:0;
left:0;
bottom:0;
right:0;
.header{
    height:.37rem;
    padding:0 .1rem;
    width:100%;
    display:flex;
    justify-content:center;
    align-items:center;
    position:fixed;
    top:0;
    background:#fff;
    z-index:100;
    span{
        font-size:.15rem;
    }
    a{
        position:absolute;
        left:.1rem;
        font-size:.18rem;
    }
    button{
        position:absolute;
        right:.1rem;
        font-size:.18rem;
        background:none;
        border:none;
    }
}

.main{
    width:100%;
    overflow:hidden;
    background:#ff3f1a;
    .banner{
        width:100%;
    }
    .main_content{
        padding:.09rem;
        img{width:100%;}
    }
    .hongtang{
        height:2rem;
        position:relative;
        margin-bottom:.1rem;
        ul{
            height:1.34rem;
            bottom:0;
            display:flex;
            justify-content:center;
            align-items:center;
            position:absolute;
            margin-left:.04rem;
            border-radius:.05rem;
            background:#fff;
            li{
                display:flex;
                justify-content:center;
                flex-direction:column;
                align-items:center;
                width:.98rem;
                height:100%;
                img{
                    width:.82rem;
                }
                h6{
                    font-size:.12rem;
                    margin-top:.09rem;
                    width:.82rem;
                    overflow:hidden;
                    text-overflow:ellipsis;
                    white-space:nowrap;
                }
                p{
                    font-size:.12rem;
                    margin-top:.03rem;
                }
            }

        }
    }
}

.goods{
    width:100%;
    overflow:hidden;
    .goods_title{
        width:100%;
        display:flex;
        justify-content:center;
        img{
            width:1.3rem;
        }
    }
    ul{
        width:100%;
        display:flex;
        flex-wrap:wrap;
        padding-top:.09rem;
        justify-content:space-between;
        li{
            padding-bottom:.09rem; 
            width:49%;
            background:#fff;
            border-radius:.08rem;
            margin-bottom:.05rem;
            img{
                width:100%;
                border-radius:.08rem .08rem 0 0;
            }
            h6{
                font-weight:normal;
                margin-top:.12rem;
                font-size:.12rem;
                overflow: hidden;
                width:100%;
                padding:0 .05rem;
                text-overflow: ellipsis;
                -webkit-line-clamp:2;
                word-break:break-all;
                display:-webkit-box;
                -webkit-box-orient:vertical;
            }
            p{
                margin-top:.07rem;
                font-size:.12rem;
                padding:0 .05rem;
            }
        }
    }
}

.bottom{
    width:100%;
    display:flex;
    justify-content:center;
    margin-top:.13rem;
    margin-bottom:.1rem;
    img{
        width:1.24rem;
    }
}
`